### PR TITLE
Doctors render over text fix

### LINKED ISSUE #50: Doctors render above text on login page
image

Solvable using z-index, or moving the doctors div before the content

### PR DESCRIPTION
**Pull request by fordacious**
closes #50

### CODE REVIEW

**Comment by fordacious** [comment]
Is there a defined width and height for this app, or is it just a standard web app?

**Comment by ibeckermayer** [comment]
> Is there a defined width and height for this app, or is it just a standard web app?

It's a standard web app, expect it to run on government employee's computers

**Comment by fordacious** [comment]
What resolution are you testing at?

**Comment by ibeckermayer** [comment]
> What resolution are you testing at?

Screen Shot 2020-05-11 at 7 51 25 PM

**Comment by fordacious** [comment]
looks like it has to be < 790px height to overlap.

**Pull request merged**
